name: Develop in Branch
on:
  [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - uses: devops-actions/actionlint@v0.1.2
      - run: echo "PR title is '${{ github.event.pull_request.title }}'."

      - run: |
          echo "::debug::This is a debug message."
          echo "::notice::This is a notice message."
          echo "::warning::This is a warning message."
          echo "::error::This is an error message."